apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ocho-wordpress.fullname" . }}-mariadb
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
data:
---
apiVersion: mariadb.mmontes.io/v1alpha1
kind: Database
metadata:
  name: {{ include "ocho-wordpress.fullname" . }}
spec:
  mariaDbRef:
    name: mariadb
    namespace: ocho-svc
  characterSet: utf8
  collate: utf8_general_ci
---
apiVersion: mariadb.mmontes.io/v1alpha1
kind: User
metadata:
  name: {{ include "ocho-wordpress.fullname" . }}
spec:
  mariaDbRef:
    name: mariadb
    namespace: ocho-svc
  passwordSecretKeyRef:
    name: {{ include "ocho-wordpress.fullname" . }}-mariadb
    key: password
  maxUserConnections: 20
  host: "%"
  requeueInterval: 30s
  retryInterval: 5s
---
apiVersion: mariadb.mmontes.io/v1alpha1
kind: Grant
metadata:
  name: {{ include "ocho-wordpress.fullname" . }}
spec:
  mariaDbRef:
    name: mariadb
    namespace: ocho-svc
  privileges:
    - "SELECT"
    - "INSERT"
    - "UPDATE"
    - "CREATE"
    - "DELETE"
  database: {{ include "ocho-wordpress.fullname" . }}
  table: "*"
  username: {{ include "ocho-wordpress.fullname" . }}