apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ocho-wordpress.fullname" . }}-uploads
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi