apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mailpit
  namespace: ocho-svc
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - mailpit.{{ .Values.tld }}
      secretName: ocho-local-tls
  rules:
  - host: mailpit.{{ .Values.tld }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: ocho-svc-mailpit-http
            port:
              number: 80
