apiVersion: v1
kind: Secret
metadata:
  name: mariadb
  namespace: ocho-svc
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
data:
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-root
  namespace: ocho-svc
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
data:
