name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          
      - name: Install Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
        with:
          version: v3.13.1

      - name: Add dependency chart repos
        run: |
          helm repo add mittwald https://helm.mittwald.de
          helm repo add jouve https://jouve.github.io/charts
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo add mariadb-operator https://mariadb-operator.github.io/mariadb-operator
          helm dependency update ./charts/ocho-services

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
